### ISSUE TITLE
Errors are ignored?

### ISSUE THREAD

**Issue by CamiloMM** [dcodeIO/grunt-closurecompiler#3]
Hi, I just got started with Node and Grunt, so this might be a misunderstanding on my part. Please bear with me :)

I'm invoking grunt-closurecompiler from the gruntfile, and for some reason errors are not caught when I run `grunt`, which reports no errors and exits with code `0`:  
![image](https://f.cloud.github.com/assets/2404138/511311/89a77238-bdff-11e2-9cae-00433951f1c8.png)

This is on Windows, with Oracle's Java. Is this an issue with `grunt-closurecompiler`? Or do I have to do something to make it all fail if compilation has an error/warning? (I'd like it to fail on warnings too).

Thank you in advance.

**Comment by CamiloMM** [comment]
Thanks, just had to `npm install` it again, and it works like a charm! :)

**Comment by julianxhokaxhiu** [comment]
Is it possible to hide them anyhow? Like show only errors but not warnings (or both).

**Comment by dcodeIO** [comment]
There's probably an option for grunt itself. Or isn't there?

**Comment by julianxhokaxhiu** [comment]
I don't know where honestly this log is coming from. I thought it was grunt.log but it seems not.

Maybe you have a better idea of where this comes from.

**Comment by dcodeIO** [comment]
Oh, now I see.

This comes from https://github.com/dcodeIO/grunt-closurecompiler/blob/master/tests/fail.js which is an old test case for grunt-closurecompiler. Looks like you are compiling `grunt-closurecompiler/tests/*` as well or something like that. Maybe a wrong base directory given to compile?

**Comment by julianxhokaxhiu** [comment]
Nope it's impossible, I'm using relative paths to my project and I'm cherry picking one single file from bower_components ( you can see it here: https://github.com/julianxhokaxhiu/mockups-creator/blob/master/Gruntfile.js#L236 ) so I think that somehow it's got by default from somewhere :(

**Comment by dcodeIO** [comment]
Regarding the error message from above, `.\build\graphene.js` already contains the questionable code before closurecompiler is even executed. Have you tried excluding the closurecompiler task and searching graphene.js for `I'm an error`?

It's still strange that the error is not even caught by grunt.

**Comment by julianxhokaxhiu** [comment]
I have to look at it, when I'll have some spare time. I'll keep you updated :)

**Comment by julianxhokaxhiu** [comment]
Sorry for the long wait response, but I managed to get some time today and I found that. Actually, you're writing always Warnings that are coming from CC. I would like to hide them since I'm not caring of them, I'm using linters before so anyhow I can catch them before they'll go to CC.

So, what I'm asking is: can you please add a global option for displaying errors and/or warnings? This is the if that actually manage that but not with a global option:
https://github.com/dcodeIO/grunt-closurecompiler/blob/master/tasks/closurecompiler.js#L76

Thanks in advice :)
