### ISSUE TITLE
support module option

### ISSUE THREAD

**Issue by waynecraig** [dcodeIO/grunt-closurecompiler#4]
Hello, in order to use the module option of closure, I wrote my task like this:
![qq20130709184425](https://f.cloud.github.com/assets/1623116/767549/8e579ce0-e884-11e2-8b8d-61715cf0a6f8.png)

But it did not work.
![qq20130709182204](https://f.cloud.github.com/assets/1623116/767460/b4bb4592-e881-11e2-888e-a584d58e0fcf.png)

I found that's because the compile process didn't return a result, neither trigger an error. So I modified the file closurecompiler.js like this:
![qq20130709183842](https://f.cloud.github.com/assets/1623116/767525/dd9178cc-e883-11e2-99b2-1153cd89fe06.png)

Then it work!
I suggest to check whether error is null there to support the module option.

**Comment by dcodeIO** [comment]
Thank you for reporting this! It's fixed in 0.9.5.
