### ISSUE TITLE
Gulp port?

### ISSUE THREAD

**Issue by julianxhokaxhiu** [dcodeIO/grunt-closurecompiler#8]
It would be awesome to have your script also in Gulp.

Any plans for that?

**Comment by dcodeIO** [comment]
It should be quite straight forward to port this one to Gulp. Do you want to try?

**Comment by julianxhokaxhiu** [comment]
I'll try tomorrow then :) thanks

**Comment by julianxhokaxhiu** [comment]
As promised, this is my first try: https://github.com/julianxhokaxhiu/gulp-closurecompiler

I'm not a Gulp guru and maybe you can point me some better techniques that I don't know.

Thanks in advice for any help :)

**Comment by dcodeIO** [comment]
That's great! I assume that people will start testing it soon as it becomes available through npm :)

**Comment by julianxhokaxhiu** [comment]
I'm going to submit it to NPM later today or at least tomorrow :) Thanks for being interested!

Closing this issue since now it's "resolved" :D
